### SendEmail
POST {{baseUrl}}/api/auth/verification-code
Accept: application/json
Content-Type: application/json

{
  "email": "liuzwmail@gmail.com"
}

### CodeSignIn
POST {{baseUrl}}/api/auth/sign-in/code
Content-Type: application/json

{
  "email": "liuzwmail@gmail.com",
  "code": "485033"
}
