@email=user1@email.com

### Home
GET {{baseUrl}}/api/home

### Check
GET {{baseUrl}}/api/user/check/{{email}}

### SendEmail
POST {{baseUrl}}/api/auth/verification-code
Accept: application/json
Content-Type: application/json

{
  "email": "{{email}}"
}

### CodeSignIn
POST {{baseUrl}}/api/auth/sign-in/code
Content-Type: application/json

{
  "email": "{{email}}",
  "code": "128658"
}

> {%
    client.global.set("accessToken",response.body["accessToken"])
%}

### User
GET {{baseUrl}}/api/user
Authorization: Bearer {{accessToken}}
Accept: application/json

### ChangePassword
PUT {{baseUrl}}/api/user/password
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "newPassword": "123456"
}

### Levels
GET {{baseUrl}}/api/referral/levels

### Referrer
GET {{baseUrl}}/api/referral/referrer
Authorization: Bearer {{accessToken}}

### Recommendees
GET {{baseUrl}}/api/referral/recommendees?sorting=totalCommission desc
Authorization: Bearer {{accessToken}}

### Applying
POST {{baseUrl}}/api/referral/request
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "levelId": "shareholder"
}

### GetApply
GET {{baseUrl}}/api/referral/request
Authorization: Bearer {{accessToken}}

### Commissions
GET {{baseUrl}}/api/commissions
Authorization: Bearer {{accessToken}}